@startuml class
skinparam classAttributeIconSize 0
class Пайдаланушы {
  - id: int
  - толықАты: string
  - email: string
  - телефон: string
  - құпиясөзХэш: string
  - рөл: Рөл
  + тіркелу()
  + кіру()
  + шығу()
}
class Көрермен {
  - тууКүні: date
  + сеансІздеу()
  + брондауЖасау()
  + билетТарихынҚарау()
}
class Қызметкер {
  - лауазымы: string
  - жұмысқаКіргенКүні: date
  + ауысымҚорытындысы()
}
class Фильм {
  - id: int
  - атауы: string
  - жанры: string
  - ұзақтығы: int
  - жасШектеуі: int
  - сипаттамасы: text
  + қосу()
  + өзгерту()
  + прокаттанАлу()
}
class Кинозал {
  - id: int
  - атауы: string
  - қатарСаны: int
  - қатардағыОрынСаны: int
  + сұлбаныЖүргізу()
}
class Орын {
  - id: int
  - қатар: int
  - нөмір: int
  - күйі: Бос/Бекітілген/Сатылған
  + бекіту()
  + босату()
}
class Сеанс {
  - id: int
  - басталуУақыты: datetime
  - бағасы: decimal
  - күйі: string
  + getSeatMap()
  + қиылысуТексеру()
}
class Брондау {
  - id: int
  - күйі: Бекітілген/Төленді/Мерзімі өтті
  - құрылғанУақыты: datetime
  - аяқталуУақыты: datetime
  + reserve()
  + confirm()
  + release()
}
class Билет {
  - id: int
  - qrКод: string
  - бағасы: decimal
  - күйі: Жарамды/Қолданылды/Қайтарылды
  + generateQR()
  + validate()
  + markUsed()
  + refund()
}
class Төлем {
  - id: int
  - сомасы: decimal
  - тәсілі: string
  - күйі: string
  - төленгенУақыты: datetime
  + process()
  + refund()
}
class ТопБрондау {
  - id: int
  - шақыруСілтемесі: string
  - төлемМерзімі: datetime
  + шақыру()
  + төленбегенДіБосату()
}
class ТағамТапсырысы {
  - id: int
  - күйі: Қабылданды/Дайын/Берілді
  - qrКод: string
  - жалпыСома: decimal
  + күйінЖаңарту()
  + беру()
}
class МәзірПозициясы {
  - id: int
  - атауы: string
  - бағасы: decimal
  - санаты: string
  + бағасынӨзгерту()
}
class Хабарлама {
  - id: int
  - түрі: string
  - арнасы: e-mail/SMS/push
  - мәтіні: text
  - жіберілгенУақыты: datetime
  + send()
}
class Есеп {
  - id: int
  - түрі: string
  - кезең: string
  - жасалғанУақыты: datetime
  + generate()
}

Көрермен --|> Пайдаланушы
Қызметкер --|> Пайдаланушы
Фильм "1" -- "0..*" Сеанс
Кинозал "1" -- "0..*" Сеанс
Кинозал "1" *-- "1..*" Орын
Сеанс "1" -- "0..*" Брондау
Көрермен "1" -- "0..*" Брондау
Брондау "0..*" -- "1..*" Орын
Брондау "1" -- "0..1" Төлем
Брондау "1" -- "1..*" Билет
ТопБрондау "0..1" -- "1..*" Брондау
Көрермен "1" -- "0..*" ТопБрондау
Брондау "1" -- "0..*" ТағамТапсырысы
ТағамТапсырысы "*" -- "1..*" МәзірПозициясы
Хабарлама "*" -- "1" Пайдаланушы
Қызметкер "1" -- "0..*" Есеп
Қызметкер "0..1" -- "0..*" Билет
@enduml
